<?xml version="1.0" encoding="utf-8"?><Database Name="TP-DISEÑO" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HARDKILL\SQLEXPRESS;Initial Catalog=TP-DISEÑO;Integrated Security=True" SettingsObjectName="TPdeDiseño.Properties.Settings" SettingsPropertyName="TP_DISEÑOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fixture" Member="Fixture">
    <Type Name="Fixture">
      <Column Name="id_fixture" AutoSync="Never" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="eliminado" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_ronda_actual" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_competencia" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Fixture_Ronda" Member="Ronda" ThisKey="id_fixture" OtherKey="id_fixture" Type="Ronda" />
      <Association Name="CompetenciaDeportiva_Fixture" Member="CompetenciaDeportiva" ThisKey="id_competencia" OtherKey="id_competencia" Type="CompetenciaDeportiva" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Participante" Member="Participante">
    <Type Name="Participante">
      <Column Name="id_participante" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[e-mail]" Member="e_mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imagen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="perdido" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="eliminado" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_competencia" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Participante_Partido_Participante" Member="Partido_Participante" ThisKey="id_participante" OtherKey="id_participante" Type="Partido_Participante" />
      <Association Name="Participante_Ronda" Member="Ronda" ThisKey="id_participante" OtherKey="id_libre" Type="Ronda" />
      <Association Name="CompetenciaDeportiva_Participante" Member="CompetenciaDeportiva" ThisKey="id_competencia" OtherKey="id_competencia" Type="CompetenciaDeportiva" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompetenciaDeportiva" Member="CompetenciaDeportiva">
    <Type Name="CompetenciaDeportiva">
      <Column Name="id_competencia" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Reglamento" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_baja" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="eliminado" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[e-mail_usuario]" Member="e_mail_usuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_deporte" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="id_modalidad" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="CompetenciaDeportiva_Fixture" Member="Fixture" ThisKey="id_competencia" OtherKey="id_competencia" Type="Fixture" />
      <Association Name="CompetenciaDeportiva_Participante" Member="Participante" ThisKey="id_competencia" OtherKey="id_competencia" Type="Participante" />
    </Type>
  </Table>
  <Table Name="dbo.Partido_Participante" Member="Partido_Participante">
    <Type Name="Partido_Participante">
      <Column Name="id_partido" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="id_participante" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Participante_Partido_Participante" Member="Participante" ThisKey="id_participante" OtherKey="id_participante" Type="Participante" IsForeignKey="true" />
      <Association Name="Partido_Partido_Participante" Member="Partido" ThisKey="id_partido" OtherKey="id_partido" Type="Partido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ronda" Member="Ronda">
    <Type Name="Ronda">
      <Column Name="nro_ronda" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="id_fixture" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ronda_perdedores" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_libre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_ronda" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Ronda_Partido" Member="Partido" ThisKey="nro_ronda" OtherKey="id_ronda" Type="Partido" />
      <Association Name="Fixture_Ronda" Member="Fixture" ThisKey="id_fixture" OtherKey="id_fixture" Type="Fixture" IsForeignKey="true" />
      <Association Name="Participante_Ronda" Member="Participante" ThisKey="id_libre" OtherKey="id_participante" Type="Participante" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Partido" Member="Partido">
    <Type Name="Partido">
      <Column Name="id_partido" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_ronda" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_lugar" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Partido_Partido_Participante" Member="Partido_Participante" ThisKey="id_partido" OtherKey="id_partido" Type="Partido_Participante" />
      <Association Name="Ronda_Partido" Member="Ronda" ThisKey="id_ronda" OtherKey="nro_ronda" Type="Ronda" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>